//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Планирование нового года шаблон")]
        public string SHEET_NAME_PLANNING_TEMPLATE {
            get {
                return ((string)(this["SHEET_NAME_PLANNING_TEMPLATE"]));
            }
            set {
                this["SHEET_NAME_PLANNING_TEMPLATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductCalendarPath {
            get {
                return ((string)(this["ProductCalendarPath"]));
            }
            set {
                this["ProductCalendarPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BudgetPath {
            get {
                return ((string)(this["BudgetPath"]));
            }
            set {
                this["BudgetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DecisionPath {
            get {
                return ((string)(this["DecisionPath"]));
            }
            set {
                this["DecisionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PriceListMTPath {
            get {
                return ((string)(this["PriceListMTPath"]));
            }
            set {
                this["PriceListMTPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlanningNYCell")]
        public string PlannningNYIndicatorCellName {
            get {
                return ((string)(this["PlannningNYIndicatorCellName"]));
            }
            set {
                this["PlannningNYIndicatorCellName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DatabaseStat")]
        public string SHEET_NAME_FILE_BUGET {
            get {
                return ((string)(this["SHEET_NAME_FILE_BUGET"]));
            }
            set {
                this["SHEET_NAME_FILE_BUGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Цены клиентов")]
        public string SHEET_NAME_FILE_PRICELISTMT {
            get {
                return ((string)(this["SHEET_NAME_FILE_PRICELISTMT"]));
            }
            set {
                this["SHEET_NAME_FILE_PRICELISTMT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database")]
        public string SHEET_NAME_FILE_DECISION {
            get {
                return ((string)(this["SHEET_NAME_FILE_DECISION"]));
            }
            set {
                this["SHEET_NAME_FILE_DECISION"] = value;
            }
        }
    }
}
